insert into app_constants
  (label, value, type, active, created_at, changed_at)
values
  ('Cat', 'cat', 'species', TRUE, now(), now()),
  ('Reptile', 'reptile', 'species', TRUE, now(), now()),
  ('Dog', 'dog', 'species', TRUE, now(), now()),
  ('Email', 'email', 'source', TRUE, now(), now()),
  ('Phone Call', 'phone call', 'source', TRUE, now(), now()),
  ('Surgery', 'surgery', 'category', TRUE, now(), now()),
  ('Vaccination', 'vaccination', 'category', TRUE, now(), now());

  INSERT INTO team_members (first_name, last_name, email, created_at) 
  VALUES
    ('John', 'Doe', 'john.doe@example.com', now()),
    ('Jane', 'Smith', 'jane.smith@example.com', now()),
    ('Michael', 'Brown', 'michael.brown@example.com', now()),
    ('Emily', 'Davis', 'emily.davis@example.com', now()),
    ('Matthew', 'Johnson', 'matthew.johnson@example.com', now()),
    ('Sophia', 'Miller', 'sophia.miller@example.com', now()),
    ('James', 'Wilson', 'james.wilson@example.com', now()),
    ('Olivia', 'Moore', 'olivia.moore@example.com', now()),
    ('William', 'Taylor', 'william.taylor@example.com', now()),
    ('Isabella', 'Anderson', 'isabella.anderson@example.com', now()),
    ('Alexander', 'Thomas', 'alexander.thomas@example.com', now()),
    ('Mia', 'Jackson', 'mia.jackson@example.com', now()),
    ('Daniel', 'White', 'daniel.white@example.com', now()),
    ('Charlotte', 'Harris', 'charlotte.harris@example.com', now()),
    ('Benjamin', 'Martin', 'benjamin.martin@example.com', now()),
    ('Amelia', 'Thompson', 'amelia.thompson@example.com', now()),
    ('Lucas', 'Garcia', 'lucas.garcia@example.com', now()),
    ('Harper', 'Martinez', 'harper.martinez@example.com', now()),
    ('Henry', 'Rodriguez', 'henry.rodriguez@example.com', now()),
    ('Evelyn', 'Martinez', 'evelyn.martinez@example.com', now()),
    ('Sebastian', 'Lopez', 'sebastian.lopez@example.com', now()),
    ('Avery', 'Gonzalez', 'avery.gonzalez@example.com', now()),
    ('Jack', 'Perez', 'jack.perez@example.com', now()),
    ('Ella', 'Hill', 'ella.hill@example.com', now()),
    ('Aiden', 'Scott', 'aiden.scott@example.com', now()),
    ('Abigail', 'Green', 'abigail.green@example.com', now()),
    ('Owen', 'Adams', 'owen.adams@example.com', now()),
    ('Scarlett', 'Baker', 'scarlett.baker@example.com', now()),
    ('Gabriel', 'Nelson', 'gabriel.nelson@example.com', now()),
    ('Chloe', 'Carter', 'chloe.carter@example.com', now());

  INSERT INTO clients (first_name, last_name, phone, email, zip_code)
  VALUES
    ('Ella', 'Hill', '(345) 678-9012', 'ella.hill@example.com', '40404'),
    ('John', 'Doe', '(123) 456-7890', 'john.doe@example.com', '10001'),
    ('Jane', 'Smith', '(234) 567-8901', 'jane.smith@example.com', '10002'),
    ('Michael', 'Brown', '(345) 678-9012', 'michael.brown@example.com', '10003'),
    ('Emily', 'Davis', '(456) 789-0123', 'emily.davis@example.com', '10004'),
    ('Matthew', 'Johnson', '(567) 890-1234', 'matthew.johnson@example.com', '10005'),
    ('Sophia', 'Miller', '(678) 901-2345', 'sophia.miller@example.com', '10006'),
    ('James', 'Wilson', '(789) 012-3456', 'james.wilson@example.com', '10007'),
    ('Olivia', 'Moore', '(890) 123-4567', 'olivia.moore@example.com', '10008'),
    ('William', 'Taylor', '(901) 234-5678', 'william.taylor@example.com', '10009'),
    ('Isabella', 'Anderson', '(012) 345-6789', 'isabella.anderson@example.com', '10010'),
    ('Alexander', 'Thomas', '(123) 456-7890', 'alexander.thomas@example.com', '10011'),
    ('Mia', 'Jackson', '(234) 567-8901', 'mia.jackson@example.com', '10012'),
    ('Daniel', 'White', '(345) 678-9012', 'daniel.white@example.com', '10013'),
    ('Charlotte', 'Harris', '(456) 789-0123', 'charlotte.harris@example.com', '10014'),
    ('Benjamin', 'Martin', '(567) 890-1234', 'benjamin.martin@example.com', '10015'),
    ('Amelia', 'Thompson', '(678) 901-2345', 'amelia.thompson@example.com', '10016'),
    ('Lucas', 'Garcia', '(789) 012-3456', 'lucas.garcia@example.com', '10017'),
    ('Harper', 'Martinez', '(890) 123-4567', 'harper.martinez@example.com', '10018'),
    ('Henry', 'Rodriguez', '(901) 234-5678', 'henry.rodriguez@example.com', '10019'),
    ('Evelyn', 'Martinez', '(012) 345-6789', 'evelyn.martinez@example.com', '10020'),
    ('Sebastian', 'Lopez', '(123) 456-7890', 'sebastian.lopez@example.com', '10021'),
    ('Avery', 'Gonzalez', '(234) 567-8901', 'avery.gonzalez@example.com', '10022'),
    ('Jack', 'Perez', '(345) 678-9012', 'jack.perez@example.com', '10023'),
    ('Ella', 'Hill', '(456) 789-0123', 'ella.hill2@example.com', '10024'),
    ('Aiden', 'Scott', '(567) 890-1234', 'aiden.scott@example.com', '10025'),
    ('Abigail', 'Green', '(678) 901-2345', 'abigail.green@example.com', '10026'),
    ('Owen', 'Adams', '(789) 012-3456', 'owen.adams@example.com', '10027'),
    ('Scarlett', 'Baker', '(890) 123-4567', 'scarlett.baker@example.com', '10028'),
    ('Gabriel', 'Nelson', '(901) 234-5678', 'gabriel.nelson@example.com', '10029'),
    ('Chloe', 'Carter', '(012) 345-6789', 'chloe.carter@example.com', '10030');

  INSERT INTO pets (name, age, weight, client_id, species)
  VALUES
  ('Max', 2, 20, (SELECT id from clients ORDER BY RANDOM() LIMIT 1), (SELECT id FROM app_constants WHERE type = 'species' ORDER BY RANDOM() LIMIT 1)),
  ('Bella', 4, 18, (SELECT id from clients ORDER BY RANDOM() LIMIT 1), (SELECT id FROM app_constants WHERE type = 'species' ORDER BY RANDOM() LIMIT 1)),
  ('Lucy', 1, 22, (SELECT id from clients ORDER BY RANDOM() LIMIT 1), (SELECT id FROM app_constants WHERE type = 'species' ORDER BY RANDOM() LIMIT 1)),
  ('Daisy', 3, 26, (SELECT id from clients ORDER BY RANDOM() LIMIT 1), (SELECT id FROM app_constants WHERE type = 'species' ORDER BY RANDOM() LIMIT 1)),
  ('Molly', 4, 19, (SELECT id from clients ORDER BY RANDOM() LIMIT 1), (SELECT id FROM app_constants WHERE type = 'species' ORDER BY RANDOM() LIMIT 1)),
  ('Bailey', 2, 23, (SELECT id from clients ORDER BY RANDOM() LIMIT 1), (SELECT id FROM app_constants WHERE type = 'species' ORDER BY RANDOM() LIMIT 1)),
  ('Maggie', 5, 21, (SELECT id from clients ORDER BY RANDOM() LIMIT 1), (SELECT id FROM app_constants WHERE type = 'species' ORDER BY RANDOM() LIMIT 1)),
  ('Sophie', 1, 27, (SELECT id from clients ORDER BY RANDOM() LIMIT 1), (SELECT id FROM app_constants WHERE type = 'species' ORDER BY RANDOM() LIMIT 1)),
  ('Sadie', 3, 24, (SELECT id from clients ORDER BY RANDOM() LIMIT 1), (SELECT id FROM app_constants WHERE type = 'species' ORDER BY RANDOM() LIMIT 1)),
  ('Lola', 2, 20, (SELECT id from clients ORDER BY RANDOM() LIMIT 1), (SELECT id FROM app_constants WHERE type = 'species' ORDER BY RANDOM() LIMIT 1)),
  ('Coco', 4, 18, (SELECT id from clients ORDER BY RANDOM() LIMIT 1), (SELECT id FROM app_constants WHERE type = 'species' ORDER BY RANDOM() LIMIT 1)),
  ('Stella', 5, 30, (SELECT id from clients ORDER BY RANDOM() LIMIT 1), (SELECT id FROM app_constants WHERE type = 'species' ORDER BY RANDOM() LIMIT 1)),
  ('Zoey', 1, 28, (SELECT id from clients ORDER BY RANDOM() LIMIT 1), (SELECT id FROM app_constants WHERE type = 'species' ORDER BY RANDOM() LIMIT 1)),
  ('Duke', 3, 26, (SELECT id from clients ORDER BY RANDOM() LIMIT 1), (SELECT id FROM app_constants WHERE type = 'species' ORDER BY RANDOM() LIMIT 1)),
  ('Harley', 2, 22, (SELECT id from clients ORDER BY RANDOM() LIMIT 1), (SELECT id FROM app_constants WHERE type = 'species' ORDER BY RANDOM() LIMIT 1)),
  ('Ruby', 4, 20, (SELECT id from clients ORDER BY RANDOM() LIMIT 1), (SELECT id FROM app_constants WHERE type = 'species' ORDER BY RANDOM() LIMIT 1)),
  ('Gracie', 5, 19, (SELECT id from clients ORDER BY RANDOM() LIMIT 1), (SELECT id FROM app_constants WHERE type = 'species' ORDER BY RANDOM() LIMIT 1)),
  ('Roxy', 1, 23, (SELECT id from clients ORDER BY RANDOM() LIMIT 1), (SELECT id FROM app_constants WHERE type = 'species' ORDER BY RANDOM() LIMIT 1)),
  ('Ginger', 3, 21, (SELECT id from clients ORDER BY RANDOM() LIMIT 1), (SELECT id FROM app_constants WHERE type = 'species' ORDER BY RANDOM() LIMIT 1)),
  ('Milo', 2, 18, (SELECT id from clients ORDER BY RANDOM() LIMIT 1), (SELECT id FROM app_constants WHERE type = 'species' ORDER BY RANDOM() LIMIT 1)),
  ('Tank', 4, 24, (SELECT id from clients ORDER BY RANDOM() LIMIT 1), (SELECT id FROM app_constants WHERE type = 'species' ORDER BY RANDOM() LIMIT 1)),
  ('Tucker', 5, 29, (SELECT id from clients ORDER BY RANDOM() LIMIT 1), (SELECT id FROM app_constants WHERE type = 'species' ORDER BY RANDOM() LIMIT 1)),
  ('Chloe', 1, 27, (SELECT id from clients ORDER BY RANDOM() LIMIT 1), (SELECT id FROM app_constants WHERE type = 'species' ORDER BY RANDOM() LIMIT 1)),
  ('Penny', 3, 25, (SELECT id from clients ORDER BY RANDOM() LIMIT 1), (SELECT id FROM app_constants WHERE type = 'species' ORDER BY RANDOM() LIMIT 1)),
  ('Ellie', 2, 22, (SELECT id from clients ORDER BY RANDOM() LIMIT 1), (SELECT id FROM app_constants WHERE type = 'species' ORDER BY RANDOM() LIMIT 1)),
  ('Jack', 4, 20, (SELECT id from clients ORDER BY RANDOM() LIMIT 1), (SELECT id FROM app_constants WHERE type = 'species' ORDER BY RANDOM() LIMIT 1)),
  ('Oliver', 5, 18, (SELECT id from clients ORDER BY RANDOM() LIMIT 1), (SELECT id FROM app_constants WHERE type = 'species' ORDER BY RANDOM() LIMIT 1)),
  ('Rosie', 1, 26, (SELECT id from clients ORDER BY RANDOM() LIMIT 1), (SELECT id FROM app_constants WHERE type = 'species' ORDER BY RANDOM() LIMIT 1)),
  ('Lily', 3, 24, (SELECT id from clients ORDER BY RANDOM() LIMIT 1), (SELECT id FROM app_constants WHERE type = 'species' ORDER BY RANDOM() LIMIT 1)),
  ('Daisy', 2, 20, (SELECT id from clients ORDER BY RANDOM() LIMIT 1), (SELECT id FROM app_constants WHERE type = 'species' ORDER BY RANDOM() LIMIT 1)),
  ('Bentley', 4, 19, (SELECT id from clients ORDER BY RANDOM() LIMIT 1), (SELECT id FROM app_constants WHERE type = 'species' ORDER BY RANDOM() LIMIT 1)),
  ('Riley', 5, 23, (SELECT id from clients ORDER BY RANDOM() LIMIT 1), (SELECT id FROM app_constants WHERE type = 'species' ORDER BY RANDOM() LIMIT 1)),
  ('Jake', 1, 21, (SELECT id from clients ORDER BY RANDOM() LIMIT 1), (SELECT id FROM app_constants WHERE type = 'species' ORDER BY RANDOM() LIMIT 1)),
  ('Marley', 3, 29, (SELECT id from clients ORDER BY RANDOM() LIMIT 1), (SELECT id FROM app_constants WHERE type = 'species' ORDER BY RANDOM() LIMIT 1)),
  ('Sasha', 2, 27, (SELECT id from clients ORDER BY RANDOM() LIMIT 1), (SELECT id FROM app_constants WHERE type = 'species' ORDER BY RANDOM() LIMIT 1)),
  ('Cody', 4, 25, (SELECT id from clients ORDER BY RANDOM() LIMIT 1), (SELECT id FROM app_constants WHERE type = 'species' ORDER BY RANDOM() LIMIT 1)),
  ('Maddie', 5, 22, (SELECT id from clients ORDER BY RANDOM() LIMIT 1), (SELECT id FROM app_constants WHERE type = 'species' ORDER BY RANDOM() LIMIT 1)),
  ('Mia', 1, 20, (SELECT id from clients ORDER BY RANDOM() LIMIT 1), (SELECT id FROM app_constants WHERE type = 'species' ORDER BY RANDOM() LIMIT 1)),
  ('Luna', 3, 28, (SELECT id from clients ORDER BY RANDOM() LIMIT 1), (SELECT id FROM app_constants WHERE type = 'species' ORDER BY RANDOM() LIMIT 1)),
  ('Zoe', 2, 26, (SELECT id from clients ORDER BY RANDOM() LIMIT 1), (SELECT id FROM app_constants WHERE type = 'species' ORDER BY RANDOM() LIMIT 1)),
  ('Rocky', 4, 19, (SELECT id from clients ORDER BY RANDOM() LIMIT 1), (SELECT id FROM app_constants WHERE type = 'species' ORDER BY RANDOM() LIMIT 1)),
  ('Buster', 5, 30, (SELECT id from clients ORDER BY RANDOM() LIMIT 1), (SELECT id FROM app_constants WHERE type = 'species' ORDER BY RANDOM() LIMIT 1)),
  ('Sam', 1, 22, (SELECT id from clients ORDER BY RANDOM() LIMIT 1), (SELECT id FROM app_constants WHERE type = 'species' ORDER BY RANDOM() LIMIT 1)),
  ('Oscar', 3, 20, (SELECT id from clients ORDER BY RANDOM() LIMIT 1), (SELECT id FROM app_constants WHERE type = 'species' ORDER BY RANDOM() LIMIT 1)),
  ('Nala', 2, 18, (SELECT id from clients ORDER BY RANDOM() LIMIT 1), (SELECT id FROM app_constants WHERE type = 'species' ORDER BY RANDOM() LIMIT 1)),
  ('Toby', 4, 21, (SELECT id from clients ORDER BY RANDOM() LIMIT 1), (SELECT id FROM app_constants WHERE type = 'species' ORDER BY RANDOM() LIMIT 1));

INSERT INTO service_requests (description,pet_id,client_id,team_member_id,service_category,request_source,status, urgent)
VALUES
  ('eating too much', (SELECT id from pets ORDER BY RANDOM() LIMIT 1),(SELECT id from clients ORDER BY RANDOM() LIMIT 1),(SELECT id from team_members ORDER BY RANDOM() LIMIT 1),(SELECT id from app_constants WHERE type = 'category'ORDER BY RANDOM() LIMIT 1),(SELECT id from app_constants WHERE type = 'source' ORDER BY RANDOM() LIMIT 1), 'open', false),
  ('limping', (SELECT id from pets ORDER BY RANDOM() LIMIT 1),(SELECT id from clients ORDER BY RANDOM() LIMIT 1),(SELECT id from team_members ORDER BY RANDOM() LIMIT 1),(SELECT id from app_constants WHERE type = 'category'ORDER BY RANDOM() LIMIT 1),(SELECT id from app_constants WHERE type = 'source' ORDER BY RANDOM() LIMIT 1), 'complete', true),
  ('not eating', (SELECT id from pets ORDER BY RANDOM() LIMIT 1),(SELECT id from clients ORDER BY RANDOM() LIMIT 1),(SELECT id from team_members ORDER BY RANDOM() LIMIT 1),(SELECT id from app_constants WHERE type = 'category'ORDER BY RANDOM() LIMIT 1),(SELECT id from app_constants WHERE type = 'source' ORDER BY RANDOM() LIMIT 1), 'pending', true),
  ('scratching constantly', (SELECT id from pets ORDER BY RANDOM() LIMIT 1),(SELECT id from clients ORDER BY RANDOM() LIMIT 1),(SELECT id from team_members ORDER BY RANDOM() LIMIT 1),(SELECT id from app_constants WHERE type = 'category'ORDER BY RANDOM() LIMIT 1),(SELECT id from app_constants WHERE type = 'source' ORDER BY RANDOM() LIMIT 1), 'open', true),
  ('vomiting', (SELECT id from pets ORDER BY RANDOM() LIMIT 1),(SELECT id from clients ORDER BY RANDOM() LIMIT 1),(SELECT id from team_members ORDER BY RANDOM() LIMIT 1),(SELECT id from app_constants WHERE type = 'category'ORDER BY RANDOM() LIMIT 1),(SELECT id from app_constants WHERE type = 'source' ORDER BY RANDOM() LIMIT 1), 'complete', true),
  ('coughing', (SELECT id from pets ORDER BY RANDOM() LIMIT 1),(SELECT id from clients ORDER BY RANDOM() LIMIT 1),(SELECT id from team_members ORDER BY RANDOM() LIMIT 1),(SELECT id from app_constants WHERE type = 'category'ORDER BY RANDOM() LIMIT 1),(SELECT id from app_constants WHERE type = 'source' ORDER BY RANDOM() LIMIT 1), 'pending', true),
  ('itchy skin', (SELECT id from pets ORDER BY RANDOM() LIMIT 1),(SELECT id from clients ORDER BY RANDOM() LIMIT 1),(SELECT id from team_members ORDER BY RANDOM() LIMIT 1),(SELECT id from app_constants WHERE type = 'category'ORDER BY RANDOM() LIMIT 1),(SELECT id from app_constants WHERE type = 'source' ORDER BY RANDOM() LIMIT 1), 'open', true),
  ('losing fur', (SELECT id from pets ORDER BY RANDOM() LIMIT 1),(SELECT id from clients ORDER BY RANDOM() LIMIT 1),(SELECT id from team_members ORDER BY RANDOM() LIMIT 1),(SELECT id from app_constants WHERE type = 'category'ORDER BY RANDOM() LIMIT 1),(SELECT id from app_constants WHERE type = 'source' ORDER BY RANDOM() LIMIT 1), 'complete', false),
  ('ear infection', (SELECT id from pets ORDER BY RANDOM() LIMIT 1),(SELECT id from clients ORDER BY RANDOM() LIMIT 1),(SELECT id from team_members ORDER BY RANDOM() LIMIT 1),(SELECT id from app_constants WHERE type = 'category'ORDER BY RANDOM() LIMIT 1),(SELECT id from app_constants WHERE type = 'source' ORDER BY RANDOM() LIMIT 1), 'pending', false),
  ('dehydration', (SELECT id from pets ORDER BY RANDOM() LIMIT 1),(SELECT id from clients ORDER BY RANDOM() LIMIT 1),(SELECT id from team_members ORDER BY RANDOM() LIMIT 1),(SELECT id from app_constants WHERE type = 'category'ORDER BY RANDOM() LIMIT 1),(SELECT id from app_constants WHERE type = 'source' ORDER BY RANDOM() LIMIT 1), 'open', false),
  ('injury from accident', (SELECT id from pets ORDER BY RANDOM() LIMIT 1),(SELECT id from clients ORDER BY RANDOM() LIMIT 1),(SELECT id from team_members ORDER BY RANDOM() LIMIT 1),(SELECT id from app_constants WHERE type = 'category'ORDER BY RANDOM() LIMIT 1),(SELECT id from app_constants WHERE type = 'source' ORDER BY RANDOM() LIMIT 1), 'complete', true),
  ('fleas infestation', (SELECT id from pets ORDER BY RANDOM() LIMIT 1),(SELECT id from clients ORDER BY RANDOM() LIMIT 1),(SELECT id from team_members ORDER BY RANDOM() LIMIT 1),(SELECT id from app_constants WHERE type = 'category'ORDER BY RANDOM() LIMIT 1),(SELECT id from app_constants WHERE type = 'source' ORDER BY RANDOM() LIMIT 1), 'pending', true),
  ('digestive problems', (SELECT id from pets ORDER BY RANDOM() LIMIT 1),(SELECT id from clients ORDER BY RANDOM() LIMIT 1),(SELECT id from team_members ORDER BY RANDOM() LIMIT 1),(SELECT id from app_constants WHERE type = 'category'ORDER BY RANDOM() LIMIT 1),(SELECT id from app_constants WHERE type = 'source' ORDER BY RANDOM() LIMIT 1), 'open', true),
  ('hairball trouble', (SELECT id from pets ORDER BY RANDOM() LIMIT 1),(SELECT id from clients ORDER BY RANDOM() LIMIT 1),(SELECT id from team_members ORDER BY RANDOM() LIMIT 1),(SELECT id from app_constants WHERE type = 'category'ORDER BY RANDOM() LIMIT 1),(SELECT id from app_constants WHERE type = 'source' ORDER BY RANDOM() LIMIT 1), 'complete', true),
  ('eye infection', (SELECT id from pets ORDER BY RANDOM() LIMIT 1),(SELECT id from clients ORDER BY RANDOM() LIMIT 1),(SELECT id from team_members ORDER BY RANDOM() LIMIT 1),(SELECT id from app_constants WHERE type = 'category'ORDER BY RANDOM() LIMIT 1),(SELECT id from app_constants WHERE type = 'source' ORDER BY RANDOM() LIMIT 1), 'pending', true),
  ('toothache', (SELECT id from pets ORDER BY RANDOM() LIMIT 1),(SELECT id from clients ORDER BY RANDOM() LIMIT 1),(SELECT id from team_members ORDER BY RANDOM() LIMIT 1),(SELECT id from app_constants WHERE type = 'category'ORDER BY RANDOM() LIMIT 1),(SELECT id from app_constants WHERE type = 'source' ORDER BY RANDOM() LIMIT 1), 'open', false),
  ('behavioral issues', (SELECT id from pets ORDER BY RANDOM() LIMIT 1),(SELECT id from clients ORDER BY RANDOM() LIMIT 1),(SELECT id from team_members ORDER BY RANDOM() LIMIT 1),(SELECT id from app_constants WHERE type = 'category'ORDER BY RANDOM() LIMIT 1),(SELECT id from app_constants WHERE type = 'source' ORDER BY RANDOM() LIMIT 1), 'complete', false),
  ('anxiety', (SELECT id from pets ORDER BY RANDOM() LIMIT 1),(SELECT id from clients ORDER BY RANDOM() LIMIT 1),(SELECT id from team_members ORDER BY RANDOM() LIMIT 1),(SELECT id from app_constants WHERE type = 'category'ORDER BY RANDOM() LIMIT 1),(SELECT id from app_constants WHERE type = 'source' ORDER BY RANDOM() LIMIT 1), 'pending', false),
  ('diarrhea', (SELECT id from pets ORDER BY RANDOM() LIMIT 1),(SELECT id from clients ORDER BY RANDOM() LIMIT 1),(SELECT id from team_members ORDER BY RANDOM() LIMIT 1),(SELECT id from app_constants WHERE type = 'category'ORDER BY RANDOM() LIMIT 1),(SELECT id from app_constants WHERE type = 'source' ORDER BY RANDOM() LIMIT 1), 'open', false),
  ('respiratory infection', (SELECT id from pets ORDER BY RANDOM() LIMIT 1),(SELECT id from clients ORDER BY RANDOM() LIMIT 1),(SELECT id from team_members ORDER BY RANDOM() LIMIT 1),(SELECT id from app_constants WHERE type = 'category'ORDER BY RANDOM() LIMIT 1),(SELECT id from app_constants WHERE type = 'source' ORDER BY RANDOM() LIMIT 1), 'complete', false),
  ('skin allergy', (SELECT id from pets ORDER BY RANDOM() LIMIT 1),(SELECT id from clients ORDER BY RANDOM() LIMIT 1),(SELECT id from team_members ORDER BY RANDOM() LIMIT 1),(SELECT id from app_constants WHERE type = 'category'ORDER BY RANDOM() LIMIT 1),(SELECT id from app_constants WHERE type = 'source' ORDER BY RANDOM() LIMIT 1), 'pending', false),
  ('nail trimming needed', (SELECT id from pets ORDER BY RANDOM() LIMIT 1),(SELECT id from clients ORDER BY RANDOM() LIMIT 1),(SELECT id from team_members ORDER BY RANDOM() LIMIT 1),(SELECT id from app_constants WHERE type = 'category'ORDER BY RANDOM() LIMIT 1),(SELECT id from app_constants WHERE type = 'source' ORDER BY RANDOM() LIMIT 1), 'open', false),
  ('weight management', (SELECT id from pets ORDER BY RANDOM() LIMIT 1),(SELECT id from clients ORDER BY RANDOM() LIMIT 1),(SELECT id from team_members ORDER BY RANDOM() LIMIT 1),(SELECT id from app_constants WHERE type = 'category'ORDER BY RANDOM() LIMIT 1),(SELECT id from app_constants WHERE type = 'source' ORDER BY RANDOM() LIMIT 1), 'complete', false),
  ('grooming appointment', (SELECT id from pets ORDER BY RANDOM() LIMIT 1),(SELECT id from clients ORDER BY RANDOM() LIMIT 1),(SELECT id from team_members ORDER BY RANDOM() LIMIT 1),(SELECT id from app_constants WHERE type = 'category'ORDER BY RANDOM() LIMIT 1),(SELECT id from app_constants WHERE type = 'source' ORDER BY RANDOM() LIMIT 1), 'pending', false),
  ('vaccination needed', (SELECT id from pets ORDER BY RANDOM() LIMIT 1),(SELECT id from clients ORDER BY RANDOM() LIMIT 1),(SELECT id from team_members ORDER BY RANDOM() LIMIT 1),(SELECT id from app_constants WHERE type = 'category'ORDER BY RANDOM() LIMIT 1),(SELECT id from app_constants WHERE type = 'source' ORDER BY RANDOM() LIMIT 1), 'open', false),
  ('dental cleaning', (SELECT id from pets ORDER BY RANDOM() LIMIT 1),(SELECT id from clients ORDER BY RANDOM() LIMIT 1),(SELECT id from team_members ORDER BY RANDOM() LIMIT 1),(SELECT id from app_constants WHERE type = 'category'ORDER BY RANDOM() LIMIT 1),(SELECT id from app_constants WHERE type = 'source' ORDER BY RANDOM() LIMIT 1), 'complete', false),
  ('spaying/neutering', (SELECT id from pets ORDER BY RANDOM() LIMIT 1),(SELECT id from clients ORDER BY RANDOM() LIMIT 1),(SELECT id from team_members ORDER BY RANDOM() LIMIT 1),(SELECT id from app_constants WHERE type = 'category'ORDER BY RANDOM() LIMIT 1),(SELECT id from app_constants WHERE type = 'source' ORDER BY RANDOM() LIMIT 1), 'pending', false),
  ('microchipping', (SELECT id from pets ORDER BY RANDOM() LIMIT 1),(SELECT id from clients ORDER BY RANDOM() LIMIT 1),(SELECT id from team_members ORDER BY RANDOM() LIMIT 1),(SELECT id from app_constants WHERE type = 'category'ORDER BY RANDOM() LIMIT 1),(SELECT id from app_constants WHERE type = 'source' ORDER BY RANDOM() LIMIT 1), 'open', false),
  ('routine checkup', (SELECT id from pets ORDER BY RANDOM() LIMIT 1),(SELECT id from clients ORDER BY RANDOM() LIMIT 1),(SELECT id from team_members ORDER BY RANDOM() LIMIT 1),(SELECT id from app_constants WHERE type = 'category'ORDER BY RANDOM() LIMIT 1),(SELECT id from app_constants WHERE type = 'source' ORDER BY RANDOM() LIMIT 1), 'complete', true),
  ('medication refill', (SELECT id from pets ORDER BY RANDOM() LIMIT 1),(SELECT id from clients ORDER BY RANDOM() LIMIT 1),(SELECT id from team_members ORDER BY RANDOM() LIMIT 1),(SELECT id from app_constants WHERE type = 'category'ORDER BY RANDOM() LIMIT 1),(SELECT id from app_constants WHERE type = 'source' ORDER BY RANDOM() LIMIT 1), 'pending', true),
  ('boarding reservation', (SELECT id from pets ORDER BY RANDOM() LIMIT 1),(SELECT id from clients ORDER BY RANDOM() LIMIT 1),(SELECT id from team_members ORDER BY RANDOM() LIMIT 1),(SELECT id from app_constants WHERE type = 'category'ORDER BY RANDOM() LIMIT 1),(SELECT id from app_constants WHERE type = 'source' ORDER BY RANDOM() LIMIT 1), 'open', true),
  ('adoption inquiry', (SELECT id from pets ORDER BY RANDOM() LIMIT 1),(SELECT id from clients ORDER BY RANDOM() LIMIT 1),(SELECT id from team_members ORDER BY RANDOM() LIMIT 1),(SELECT id from app_constants WHERE type = 'category'ORDER BY RANDOM() LIMIT 1),(SELECT id from app_constants WHERE type = 'source' ORDER BY RANDOM() LIMIT 1), 'complete', true),
  ('lost pet report', (SELECT id from pets ORDER BY RANDOM() LIMIT 1),(SELECT id from clients ORDER BY RANDOM() LIMIT 1),(SELECT id from team_members ORDER BY RANDOM() LIMIT 1),(SELECT id from app_constants WHERE type = 'category'ORDER BY RANDOM() LIMIT 1),(SELECT id from app_constants WHERE type = 'source' ORDER BY RANDOM() LIMIT 1), 'pending', false),
  ('found stray pet', (SELECT id from pets ORDER BY RANDOM() LIMIT 1),(SELECT id from clients ORDER BY RANDOM() LIMIT 1),(SELECT id from team_members ORDER BY RANDOM() LIMIT 1),(SELECT id from app_constants WHERE type = 'category'ORDER BY RANDOM() LIMIT 1),(SELECT id from app_constants WHERE type = 'source' ORDER BY RANDOM() LIMIT 1), 'open', false),
  ('volunteer application', (SELECT id from pets ORDER BY RANDOM() LIMIT 1),(SELECT id from clients ORDER BY RANDOM() LIMIT 1),(SELECT id from team_members ORDER BY RANDOM() LIMIT 1),(SELECT id from app_constants WHERE type = 'category'ORDER BY RANDOM() LIMIT 1),(SELECT id from app_constants WHERE type = 'source' ORDER BY RANDOM() LIMIT 1), 'complete', false),
  ('donation request', (SELECT id from pets ORDER BY RANDOM() LIMIT 1),(SELECT id from clients ORDER BY RANDOM() LIMIT 1),(SELECT id from team_members ORDER BY RANDOM() LIMIT 1),(SELECT id from app_constants WHERE type = 'category'ORDER BY RANDOM() LIMIT 1),(SELECT id from app_constants WHERE type = 'source' ORDER BY RANDOM() LIMIT 1), 'pending', false),
  ('fundraising event', (SELECT id from pets ORDER BY RANDOM() LIMIT 1),(SELECT id from clients ORDER BY RANDOM() LIMIT 1),(SELECT id from team_members ORDER BY RANDOM() LIMIT 1),(SELECT id from app_constants WHERE type = 'category'ORDER BY RANDOM() LIMIT 1),(SELECT id from app_constants WHERE type = 'source' ORDER BY RANDOM() LIMIT 1), 'open', false),
  ('pet training class', (SELECT id from pets ORDER BY RANDOM() LIMIT 1),(SELECT id from clients ORDER BY RANDOM() LIMIT 1),(SELECT id from team_members ORDER BY RANDOM() LIMIT 1),(SELECT id from app_constants WHERE type = 'category'ORDER BY RANDOM() LIMIT 1),(SELECT id from app_constants WHERE type = 'source' ORDER BY RANDOM() LIMIT 1), 'complete', false),
  ('pet insurance query', (SELECT id from pets ORDER BY RANDOM() LIMIT 1),(SELECT id from clients ORDER BY RANDOM() LIMIT 1),(SELECT id from team_members ORDER BY RANDOM() LIMIT 1),(SELECT id from app_constants WHERE type = 'category'ORDER BY RANDOM() LIMIT 1),(SELECT id from app_constants WHERE type = 'source' ORDER BY RANDOM() LIMIT 1), 'pending', false),
  ('emergency pet care', (SELECT id from pets ORDER BY RANDOM() LIMIT 1),(SELECT id from clients ORDER BY RANDOM() LIMIT 1),(SELECT id from team_members ORDER BY RANDOM() LIMIT 1),(SELECT id from app_constants WHERE type = 'category'ORDER BY RANDOM() LIMIT 1),(SELECT id from app_constants WHERE type = 'source' ORDER BY RANDOM() LIMIT 1), 'open', false),
  ('pet memorial service', (SELECT id from pets ORDER BY RANDOM() LIMIT 1),(SELECT id from clients ORDER BY RANDOM() LIMIT 1),(SELECT id from team_members ORDER BY RANDOM() LIMIT 1),(SELECT id from app_constants WHERE type = 'category'ORDER BY RANDOM() LIMIT 1),(SELECT id from app_constants WHERE type = 'source' ORDER BY RANDOM() LIMIT 1), 'complete', false),
  ('pet photography session', (SELECT id from pets ORDER BY RANDOM() LIMIT 1),(SELECT id from clients ORDER BY RANDOM() LIMIT 1),(SELECT id from team_members ORDER BY RANDOM() LIMIT 1),(SELECT id from app_constants WHERE type = 'category'ORDER BY RANDOM() LIMIT 1),(SELECT id from app_constants WHERE type = 'source' ORDER BY RANDOM() LIMIT 1), 'pending', false),
  ('pet supplies purchase', (SELECT id from pets ORDER BY RANDOM() LIMIT 1),(SELECT id from clients ORDER BY RANDOM() LIMIT 1),(SELECT id from team_members ORDER BY RANDOM() LIMIT 1),(SELECT id from app_constants WHERE type = 'category'ORDER BY RANDOM() LIMIT 1),(SELECT id from app_constants WHERE type = 'source' ORDER BY RANDOM() LIMIT 1), 'open', false),
  ('pet grooming tutorial', (SELECT id from pets ORDER BY RANDOM() LIMIT 1),(SELECT id from clients ORDER BY RANDOM() LIMIT 1),(SELECT id from team_members ORDER BY RANDOM() LIMIT 1),(SELECT id from app_constants WHERE type = 'category'ORDER BY RANDOM() LIMIT 1),(SELECT id from app_constants WHERE type = 'source' ORDER BY RANDOM() LIMIT 1), 'complete', false),
  ('pet adoption event', (SELECT id from pets ORDER BY RANDOM() LIMIT 1),(SELECT id from clients ORDER BY RANDOM() LIMIT 1),(SELECT id from team_members ORDER BY RANDOM() LIMIT 1),(SELECT id from app_constants WHERE type = 'category'ORDER BY RANDOM() LIMIT 1),(SELECT id from app_constants WHERE type = 'source' ORDER BY RANDOM() LIMIT 1), 'pending', false);