name: Deploy Migrations to Production

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SUPABASE_ACCESS_TOKEN: $SUPABASE_ACCESS_TOKEN
      SUPABASE_DB_PASSWORD: ${{ secrets.PRODUCTION_DB_PASSWORD }}
      SUPABASE_PROJECT_ID: ${{ vars.PRODUCTION_PROJECT_ID }}
      SUPABASE_AUTH_AZURE_CLIENT_ID: ${{ vars.SUPABASE_AUTH_AZURE_CLIENT_ID }}
      SUPABASE_AUTH_AZURE_REDIRECT_URI: ${{ vars.SUPABASE_AUTH_AZURE_REDIRECT_URI }}
      SUPABASE_AUTH_AZURE_SECRET: ${{ secrets.SUPABASE_AUTH_AZURE_SECRET }}
      SUPABASE_AUTH_AZURE_URI: ${{ vars.SUPABASE_AUTH_AZURE_URI }}


    steps:
      - uses: actions/checkout@v3

      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - run: supabase link --project-ref $SUPABASE_PROJECT_ID
      - run: supabase db push